# 自动化测试

name: test

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/**'
      - '__test__/**'
      - 'src/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: print node version
        run: |
            node -v
            npm -v
            echo 'hi'
  test2:
      runs-on: ubuntu-latest
      steps:
        - run: touch a.txt
        - run: echo 100 > a.txt
        - run: cat a.txt